# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'LiveAppSnippet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'CocoaLumberjack/Swift'
pod 'Kingfisher'
pod 'SnapKit'
pod 'RxSwift', '~> 6.5.0'
pod 'RxRelay', '~> 6.5.0'
pod 'RxCocoa', '~> 6.5.0'
pod 'IGListKit', '~> 4.0.0'
pod 'YYText'


end
